jobs:
- job: van_winkel_financial_database
  pool: 'default'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: |
      cd $(Build.SourcesDirectory)/src/Van.Winkel.Financial.Database
      dotnet build --configuration $(buildConfiguration)
      dotnet publish --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/van-winkel-financial-database

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()