name: Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, features/**, bugs/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
      working-directory: ./src/Van.Winkel.Frontend
    - name: Build
      run: npm run build:ci
      working-directory: ./src/Van.Winkel.Frontend
